version: '3.8'

services:
  knapsack-api-node:
    build: .
    ports:
      - "7000:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
